"use client";

import React, { createContext, useContext, useState, ReactNode } from "react";

export type Language = "en" | "no";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined,
);

const translations = {
  en: {
    "spelling.practice": "Spelling Practice",
    score: "Score",
    "new.word": "New Word",
    "start.practice": "Start Practice",
    "spell.this.word": "Spell this word:",
    listen: "Listen",
    "type.word.here": "Type the word here...",
    "check.spelling": "Check Spelling",
    correct: "Correct!",
    "not.quite": "Not quite! The correct spelling is:",
    "nav.home": "Home",
    "nav.practice": "Practice",
    "nav.about": "About",
    "nav.profile": "Profile",
    "nav.wordsets": "Word Sets",
    "nav.results": "Results",
    "home.welcome": "Welcome to Diktator!",
    "home.subtitle":
      "A fun and interactive spelling practice app designed especially for children",
    "home.api.checking": "Checking API...",
    "home.api.connected": "API Connected",
    "home.api.disconnected": "API Disconnected",
    "home.wordsets.title": "Word Sets",
    "home.wordsets.desc":
      "Create and manage custom word sets, then take spelling tests to track your progress!",
    "home.wordsets.button": "Explore Word Sets",
    "home.practice.title": "Start Practicing",
    "home.practice.desc":
      "Practice spelling with our interactive word games and improve your skills!",
    "home.practice.button": "Begin Practice",
    // Practice page
    "practice.title": "Spelling Practice",
    "practice.subtitle": "Choose a word set to practice your spelling skills",
    "practice.noWordSets": "No word sets available",
    "practice.createFirst": "Create your first word set to start practicing",
    "practice.createWordSet": "Create Word Set",
    "practice.start": "Start Practice",
    "practice.clickToHear": "Click to hear the word",
    "practice.playAgain": "Click to hear again",
    "practice.typeHere": "Type the word here...",
    "practice.checkAnswer": "Check Answer",
    "practice.correct": "Correct!",
    "practice.incorrect": "Not quite right",
    "practice.correctSpelling": "Correct spelling",
    "practice.yourAnswer": "Your answer",
    "practice.nextWordSoon": "Moving to next word...",
    "practice.practiceComplete": "Practice complete!",
    "practice.correctSoFar": "Correct so far",
    "practice.attempt": "Attempt",
    "practice.attemptsLeft": "attempts left",
    "practice.tryAgain": "Try Again",
    "practice.maxAttemptsReached": "Max attempts reached",
    "practice.configuration.title": "Test Configuration",
    "practice.configuration.maxAttempts": "Max attempts per word",
    "practice.configuration.showCorrectAnswer":
      "Show correct answer after failure",
    "practice.configuration.autoAdvance": "Auto-advance after correct answer",
    "common.words": "words",
    "common.back": "Back",
    "home.about.title": "Learn More",
    "home.about.desc":
      "Discover how Diktator can help children develop better spelling skills.",
    "home.about.button": "About Us",
    // Home features section
    "home.features.title": "Ready to Practice!",
    "home.features.subtitle":
      "Advanced spelling practice with audio feedback and professional user experience.",
    "home.features.auth": "Firebase Authentication",
    "home.features.database": "Firestore Database",
    "home.features.i18n": "Multilingual Support (EN/NO)",
    "home.features.wordsets": "Custom Word Sets & Tests",
    "home.features.profiles": "User Profiles & Statistics",
    "home.features.tts": "Speech Synthesis (TTS)",
    "home.features.results": "Test Results Tracking",
    "home.features.emulators": "Firebase Emulators",
    "home.nextPhase.title": "Ready for Phase 2:",
    "home.nextPhase.desc":
      "Custom word sets, family sharing, and advanced analytics",
    "home.nextPhase.command": "Start development",
    "home.phaseComplete.title": "Fully Featured!",
    "home.phaseComplete.desc":
      "All core features are ready for an optimal spelling practice experience",
    "home.phaseComplete.features":
      "✨ Audio feedback, visual animations, progress tracking, and responsive design",

    // Development progress section
    "home.progress.title": "Development Progress",
    "home.progress.subtitle": "Track our journey building the ultimate spelling practice app",

    // Phase 0
    "home.progress.phase0.title": "Foundation",
    "home.progress.phase0.subtitle": "Core Infrastructure",
    "home.progress.phase0.point1": "Next.js + TypeScript setup",
    "home.progress.phase0.point2": "Google Cloud deployment",
    "home.progress.phase0.point3": "CI/CD pipeline established",

    // Phase 1
    "home.progress.phase1.title": "Authentication",
    "home.progress.phase1.subtitle": "User Management",
    "home.progress.phase1.point1": "Firebase Authentication",
    "home.progress.phase1.point2": "Protected routes & security",
    "home.progress.phase1.point3": "User profiles & families",

    // Phase 2
    "home.progress.phase2.title": "Core Features",
    "home.progress.phase2.subtitle": "Spelling Practice",
    "home.progress.phase2.point1": "Word set management",
    "home.progress.phase2.point2": "Text-to-Speech integration",
    "home.progress.phase2.point3": "Interactive spelling tests",

    // Phase 3
    "home.progress.phase3.title": "Advanced",
    "home.progress.phase3.subtitle": "Polish & Analytics",
    "home.progress.phase3.point1": "Progress analytics",
    "home.progress.phase3.point2": "Gamification system",
    "home.progress.phase3.point3": "Performance optimization",
    "about.title": "About Diktator",
    "about.what.title": "What is Diktator?",
    "about.what.desc":
      "Diktator is a fun and interactive spelling practice application designed specifically for children. Our goal is to make learning spelling enjoyable and engaging through modern web technology.",
    "about.features.title": "Features",
    "about.feature.1": "Interactive spelling practice with immediate feedback",
    "about.feature.2": "Audio pronunciation for each word",
    "about.feature.3": "Score tracking to monitor progress",
    "about.feature.4": "Modern, responsive design that works on all devices",
    "about.feature.5": "Single Page Application for smooth navigation",
    "about.feature.6": "Audio feedback with success tones and error sounds",
    "about.feature.7": "Professional spinner animations during audio playback",
    "about.feature.8": "Layout stability with no jarring interface shifts",
    "about.feature.9": "Automatic word replay for incorrect answers",
    "about.feature.10": "Unified input/feedback containers for clean UX",
    "about.tech.title": "Technology Stack",
    "about.tech.frontend": "Frontend",
    "about.tech.backend": "Backend",
    "about.development.title": "Development",
    "about.development.desc":
      "This application is built with modern development practices including Infrastructure as Code (Terraform), automated CI/CD pipelines (GitHub Actions), and streamlined local development using mise for task management.",
    "auth.signin.title": "Sign In",
    "auth.signin.subtitle":
      "Welcome back! Sign in to continue your spelling journey.",
    "auth.signin.button": "Sign In",
    "auth.signin.switchToSignup": "Don&apos;t have an account? Sign up",
    "auth.signup.title": "Create Account",
    "auth.signup.subtitle": "Join Diktator and start your spelling adventure!",
    "auth.signup.button": "Create Account",
    "auth.signup.switchToSignin": "Already have an account? Sign in",
    "auth.email": "Email Address",
    "auth.email.placeholder": "Enter your email",
    "auth.password": "Password",
    "auth.password.placeholder": "Enter your password",
    "auth.displayName": "Display Name",
    "auth.displayName.placeholder": "Enter your name",
    "auth.role": "Account Type",
    "auth.role.child": "Student",
    "auth.role.parent": "Parent/Teacher",
    "auth.logout": "Logout",
    "profile.title": "My Profile",
    "profile.stats.testsCompleted": "Tests Completed",
    "profile.stats.averageScore": "Average Score",
    "profile.stats.totalWords": "Total Words",
    "profile.stats.correctWords": "Correct Words",
    "profile.recentResults": "Recent Results",
    "profile.noResults": "No test results yet. Start practicing!",
    "profile.correct": "correct",
    // Word Sets page
    "wordsets.title": "Word Sets",
    "wordsets.subtitle": "Create and manage spelling word collections",
    "wordsets.create": "Create New Word Set",
    "wordsets.name": "Word Set Name",
    "wordsets.name.placeholder": "Enter word set name",
    "wordsets.language": "Language",
    "wordsets.words": "Words",
    "wordsets.addWord": "Add Word",
    "wordsets.addWord.placeholder": "Enter a word to add",
    "wordsets.save": "Save Word Set",
    "wordsets.cancel": "Cancel",
    "wordsets.delete": "Delete",
    "wordsets.startTest": "Start Test",
    "wordsets.noWordSets": "No word sets yet. Create your first one!",
    "wordsets.created": "Created",
    "wordsets.words.count": "words",
    "wordsets.createSuccess": "Word set created successfully!",
    "wordsets.createError": "Failed to create word set",
    "wordsets.loading": "Loading word sets...",
    "wordsets.add": "Add",
    "wordsets.creating": "Creating...",
    "wordsets.generateAudio": "Generate Audio",
    "wordsets.deleteConfirm": "Are you sure you want to delete this word set?",
    "wordsets.deleteSuccess": "Word set deleted successfully!",
    "wordsets.deleteError": "Failed to delete word set",
    "wordsets.audioGeneration":
      "Audio generation started! This may take a few moments.",
    "wordsets.audioError": "Failed to start audio generation",
    "wordsets.nameRequired": "Please provide a name and at least one word",
    "wordsets.noTitle": "No word sets yet",
    "wordsets.settings": "Test Settings",
    "wordsets.saveSettings": "Save Settings",
    "wordsets.config.maxAttempts": "Max Attempts",
    "wordsets.config.attempt": "attempt",
    "wordsets.config.attempts": "attempts",
    "wordsets.config.default": "default",
    "wordsets.config.autoPlayAudio": "Auto-play audio",
    "wordsets.config.shuffleWords": "Shuffle words",
    "wordsets.config.showCorrectAnswer": "Show correct answer on mistakes",
    "wordsets.config.autoAdvance": "Auto-advance to next word",
    "wordsets.config.timeLimit": "Time limit per word",
    "wordsets.config.optional": "optional",
    "wordsets.config.noTimeLimit": "No time limit",
    "wordsets.config.timeLimitHelp":
      "Leave empty for no time limit. Time in seconds (1-300).",
    "wordsets.noSubtitle": "Create your first word set to get started!",
    "wordsets.moreWords": "more",
    // Results page
    "results.title": "Test Results",
    "results.subtitle": "View your spelling test history and progress",
    "results.noResults":
      "No test results yet. Take a spelling test to see your progress!",
    "results.startFirst": "Take your first spelling test to see your progress!",
    "results.startFirstTest": "Start Your First Test",
    "results.stats.totalTests": "Total Tests",
    "results.stats.averageScore": "Average Score",
    "results.stats.bestScore": "Best Score",
    "results.stats.timeSpent": "Time Spent",
    "results.recentTests": "Recent Tests",
    "results.correct": "correct",
    "results.time": "Time",
    "results.avg": "Avg",
    "results.word": "word",
    "results.wordsToPractice": "Words to practice",
    "results.spellingChampion": "Spelling Champion!",
    "results.averageAbove90": "Average score above 90%",
    "results.dedicatedLearner": "Dedicated Learner!",
    "results.completedTests": "Completed",
    "results.tests": "tests",
    "common.loading": "Loading...",
    // Test page
    "test.loading": "Loading test...",
    "test.notFound": "Word set not found",
    "test.backToWordSets": "Back to Word Sets",
    "test.complete": "Test Complete!",
    "test.score": "Score",
    "test.correct": "Correct",
    "test.timeSpent": "Time Spent",
    "test.averageTime": "Average Time",
    "test.seconds": "seconds",
    "test.restart": "Take Test Again",
    "test.viewResults": "View All Results",
    "test.listenToWord": "Listen to word",
    "test.yourAnswer": "Your answer:",
    "test.nextWord": "Next Word",
    "test.finishTest": "Finish Test",
    "test.progress": "Progress",
    "test.reviewMistakes": "Review Mistakes:",
    "test.reviewResults": "Review All Words:",
    "test.playAgain": "Play Again",
    "test.typeWordHere": "Type the word here...",
    "test.correctSoFar": "Correct so far",
    "test.incorrect": "Incorrect",
    "test.tryAgain": "Try again",
    "test.attemptsRemaining": "Attempts remaining",
    "common.of": "of",
  },
  no: {
    "spelling.practice": "Stavepraksis",
    score: "Poeng",
    "new.word": "Nytt ord",
    "start.practice": "Start øving",
    "spell.this.word": "Stav dette ordet:",
    listen: "Lytt",
    "type.word.here": "Skriv ordet her...",
    "check.spelling": "Sjekk staving",
    correct: "Riktig!",
    "not.quite": "Ikke helt! Riktig staving er:",
    "nav.home": "Hjem",
    "nav.practice": "Øving",
    "nav.about": "Om",
    "nav.profile": "Profil",
    "nav.wordsets": "Ordsett",
    "nav.results": "Resultater",
    "home.welcome": "Velkommen til Diktator!",
    "home.subtitle":
      "En morsom og interaktiv stavepraksis-app designet spesielt for barn",
    "home.api.checking": "Sjekker API...",
    "home.api.connected": "API tilkoblet",
    "home.api.disconnected": "API frakoblet",
    "home.wordsets.title": "Ordsett",
    "home.wordsets.desc":
      "Opprett og administrer tilpassede ordsett, og ta staveprøver for å følge fremgangen din!",
    "home.wordsets.button": "Utforsk ordsett",
    "home.practice.title": "Start å øve",
    "home.practice.desc":
      "Øv på staving med våre interaktive ordspill og forbedre ferdighetene dine!",
    "home.practice.button": "Begynn øving",
    // Practice page
    "practice.title": "Stavepraksis",
    "practice.subtitle": "Velg et ordsett for å øve på staveferdigheter",
    "practice.noWordSets": "Ingen ordsett tilgjengelig",
    "practice.createFirst": "Opprett ditt første ordsett for å begynne å øve",
    "practice.createWordSet": "Opprett ordsett",
    "practice.start": "Start øving",
    "practice.clickToHear": "Klikk for å høre ordet",
    "practice.playAgain": "Klikk for å høre igjen",
    "practice.typeHere": "Skriv ordet her...",
    "practice.checkAnswer": "Sjekk svar",
    "practice.correct": "Riktig!",
    "practice.incorrect": "Ikke helt riktig",
    "practice.correctSpelling": "Korrekt staving",
    "practice.yourAnswer": "Ditt svar",
    "practice.nextWordSoon": "Går til neste ord...",
    "practice.practiceComplete": "Øving fullført!",
    "practice.correctSoFar": "Riktige så langt",
    "practice.attempt": "Forsøk",
    "practice.attemptsLeft": "forsøk igjen",
    "practice.tryAgain": "Prøv igjen",
    "practice.maxAttemptsReached": "Maks forsøk nådd",
    "practice.configuration.title": "Test konfigurasjon",
    "practice.configuration.maxAttempts": "Maks forsøk per ord",
    "practice.configuration.showCorrectAnswer": "Vis riktig svar etter feil",
    "practice.configuration.autoAdvance": "Auto-fortsett etter riktig svar",
    "common.words": "ord",
    "common.back": "Tilbake",
    "home.about.title": "Lær mer",
    "home.about.desc":
      "Oppdag hvordan Diktator kan hjelpe barn med å utvikle bedre staveferdigheter.",
    "home.about.button": "Om oss",
    // Home features section
    "home.features.title": "Klar for øving!",
    "home.features.subtitle":
      "Avansert stavingsøving med lydtilbakemelding og profesjonell brukeropplevelse.",
    "home.features.auth": "Firebase autentisering",
    "home.features.database": "Firestore database",
    "home.features.i18n": "Flerspråklig støtte (EN/NO)",
    "home.features.wordsets": "Tilpassede ordsett og tester",
    "home.features.profiles": "Brukerprofiler og statistikk",
    "home.features.tts": "Talesyntese (TTS)",
    "home.features.results": "Testresultater sporing",
    "home.features.emulators": "Firebase emulatorer",
    "home.nextPhase.title": "Klar for fase 2:",
    "home.nextPhase.desc":
      "Tilpassede ordsett, familiedeling og avansert analyse",
    "home.nextPhase.command": "Start utvikling",
    "home.phaseComplete.title": "Fullstendig utstyrt!",
    "home.phaseComplete.desc":
      "Alle kjernefunksjoner er klare for en optimal stavingsøvingsopplevelse",
    "home.phaseComplete.features":
      "✨ Lydtilbakemelding, visuelle animasjoner, fremdriftssporing og responsivt design",

    // Development progress section
    "home.progress.title": "Utviklingsfremdrift",
    "home.progress.subtitle": "Følg vår reise mot den ultimate stavingsøvingsappen",

    // Phase 0
    "home.progress.phase0.title": "Grunnlag",
    "home.progress.phase0.subtitle": "Grunnleggende infrastruktur",
    "home.progress.phase0.point1": "Next.js + TypeScript oppsett",
    "home.progress.phase0.point2": "Google Cloud distribusjon",
    "home.progress.phase0.point3": "CI/CD-pipeline etablert",

    // Phase 1
    "home.progress.phase1.title": "Autentisering",
    "home.progress.phase1.subtitle": "Brukerbehandling",
    "home.progress.phase1.point1": "Firebase autentisering",
    "home.progress.phase1.point2": "Beskyttede ruter og sikkerhet",
    "home.progress.phase1.point3": "Brukerprofiler og familier",

    // Phase 2
    "home.progress.phase2.title": "Kjernefunksjoner",
    "home.progress.phase2.subtitle": "Stavingsøving",
    "home.progress.phase2.point1": "Ordsettbehandling",
    "home.progress.phase2.point2": "Tekst-til-tale integrasjon",
    "home.progress.phase2.point3": "Interaktive stavingstester",

    // Phase 3
    "home.progress.phase3.title": "Avansert",
    "home.progress.phase3.subtitle": "Polering og analyse",
    "home.progress.phase3.point1": "Fremdriftsanalyse",
    "home.progress.phase3.point2": "Spillifiseringssystem",
    "home.progress.phase3.point3": "Ytelsesoptimalisering",
    "about.title": "Om Diktator",
    "about.what.title": "Hva er Diktator?",
    "about.what.desc":
      "Diktator er en morsom og interaktiv stavepraksis-applikasjon designet spesielt for barn. Vårt mål er å gjøre ståvelæring hyggelig og engasjerende gjennom moderne webteknologi.",
    "about.features.title": "Funksjoner",
    "about.feature.1": "Interaktiv stavepraksis med umiddelbar tilbakemelding",
    "about.feature.2": "Lyduttalelse for hvert ord",
    "about.feature.3": "Poengsporing for å overvåke fremgang",
    "about.feature.4":
      "Moderne, responsivt design som fungerer på alle enheter",
    "about.feature.5": "Single Page Application for smidig navigering",
    "about.feature.6": "Lydtilbakemelding med suksess-toner og feil-lyder",
    "about.feature.7": "Profesjonelle spinner-animasjoner under lydavspilling",
    "about.feature.8": "Layout-stabilitet uten forstyrrende grensesnitt-endringer",
    "about.feature.9": "Automatisk ord-repetisjon for feil svar",
    "about.feature.10": "Enhetlige input/tilbakemelding-containere for ren UX",
    "about.tech.title": "Teknologistakk",
    "about.tech.frontend": "Frontend",
    "about.tech.backend": "Backend",
    "about.development.title": "Utvikling",
    "about.development.desc":
      "Denne applikasjonen er bygget med moderne utviklingspraksis inkludert Infrastructure as Code (Terraform), automatiserte CI/CD-pipelines (GitHub Actions), og strømlinjeformet lokal utvikling med mise for oppgavehåndtering.",
    "auth.signin.title": "Logg inn",
    "auth.signin.subtitle":
      "Velkommen tilbake! Logg inn for å fortsette din stavereise.",
    "auth.signin.button": "Logg inn",
    "auth.signin.switchToSignup": "Har du ikke en konto? Registrer deg",
    "auth.signup.title": "Opprett konto",
    "auth.signup.subtitle": "Bli med i Diktator og start ditt staveeventyr!",
    "auth.signup.button": "Opprett konto",
    "auth.signup.switchToSignin": "Har du allerede en konto? Logg inn",
    "auth.email": "E-postadresse",
    "auth.email.placeholder": "Skriv inn din e-post",
    "auth.password": "Passord",
    "auth.password.placeholder": "Skriv inn ditt passord",
    "auth.displayName": "Visningsnavn",
    "auth.displayName.placeholder": "Skriv inn ditt navn",
    "auth.role": "Kontotype",
    "auth.role.child": "Elev",
    "auth.role.parent": "Forelder/Lærer",
    "auth.logout": "Logg ut",
    "profile.title": "Min profil",
    "profile.stats.testsCompleted": "Tester fullført",
    "profile.stats.averageScore": "Gjennomsnittlig poengsum",
    "profile.stats.totalWords": "Totalt ord",
    "profile.stats.correctWords": "Riktige ord",
    "profile.recentResults": "Nylige resultater",
    "profile.noResults": "Ingen testresultater ennå. Start å øve!",
    "profile.correct": "riktig",
    // Word Sets page
    "wordsets.title": "Ordsett",
    "wordsets.subtitle": "Opprett og administrer stavingsordsamlinger",
    "wordsets.create": "Opprett nytt ordsett",
    "wordsets.name": "Ordsett navn",
    "wordsets.name.placeholder": "Skriv inn ordsett navn",
    "wordsets.language": "Språk",
    "wordsets.words": "Ord",
    "wordsets.addWord": "Legg til ord",
    "wordsets.addWord.placeholder": "Skriv inn et ord å legge til",
    "wordsets.save": "Lagre ordsett",
    "wordsets.cancel": "Avbryt",
    "wordsets.delete": "Slett",
    "wordsets.startTest": "Start test",
    "wordsets.noWordSets": "Ingen ordsett ennå. Opprett ditt første!",
    "wordsets.created": "Opprettet",
    "wordsets.words.count": "ord",
    "wordsets.createSuccess": "Ordsett opprettet vellykket!",
    "wordsets.createError": "Kunne ikke opprette ordsett",
    "wordsets.loading": "Laster ordsett...",
    "wordsets.add": "Legg til",
    "wordsets.creating": "Oppretter...",
    "wordsets.generateAudio": "Generer lyd",
    "wordsets.deleteConfirm":
      "Er du sikker på at du vil slette dette ordsettet?",
    "wordsets.deleteSuccess": "Ordsett slettet vellykket!",
    "wordsets.deleteError": "Kunne ikke slette ordsett",
    "wordsets.audioGeneration":
      "Lydgenerering startet! Dette kan ta noen øyeblikk.",
    "wordsets.audioError": "Kunne ikke starte lydgenerering",
    "wordsets.nameRequired": "Vennligst oppgi et navn og minst ett ord",
    "wordsets.noTitle": "Ingen ordsett ennå",
    "wordsets.noSubtitle": "Opprett ditt første ordsett for å komme i gang!",
    "wordsets.moreWords": "flere",
    "wordsets.settings": "Test innstillinger",
    "wordsets.saveSettings": "Lagre innstillinger",
    "wordsets.config.maxAttempts": "Maks forsøk",
    "wordsets.config.attempt": "forsøk",
    "wordsets.config.attempts": "forsøk",
    "wordsets.config.default": "standard",
    "wordsets.config.autoPlayAudio": "Automatisk avspilling av lyd",
    "wordsets.config.shuffleWords": "Bland ord",
    "wordsets.config.showCorrectAnswer": "Vis riktig svar ved feil",
    "wordsets.config.autoAdvance": "Auto-gå til neste ord",
    "wordsets.config.timeLimit": "Tidsbegrensning per ord",
    "wordsets.config.optional": "valgfritt",
    "wordsets.config.noTimeLimit": "Ingen tidsbegrensning",
    "wordsets.config.timeLimitHelp":
      "La stå tom for ingen tidsbegrensning. Tid i sekunder (1-300).",
    // Results page
    "results.title": "Testresultater",
    "results.subtitle": "Se din stavingstest historie og fremgang",
    "results.noResults":
      "Ingen testresultater ennå. Ta en stavingstest for å se din fremgang!",
    "results.startFirst": "Ta din første stavingstest for å se resultater her!",
    "results.startFirstTest": "Start første test",
    "results.stats.totalTests": "Totale tester",
    "results.stats.averageScore": "Gjennomsnittlig poengsum",
    "results.stats.bestScore": "Beste poengsum",
    "results.stats.timeSpent": "Tid brukt",
    "results.recentTests": "Nylige tester",
    "results.score": "Poeng",
    "results.date": "Dato",
    "results.time": "Tid",
    "results.avg": "Snitt",
    "results.word": "ord",
    "results.words": "Ord",
    "results.correct": "riktig",
    "results.seconds": "sekunder",
    "results.wordsToPractice": "Ord å øve på",
    "results.spellingChampion": "Stavemester!",
    "results.averageAbove90": "Gjennomsnittlig poengsum over 90%",
    "results.dedicatedLearner": "Dedikert lærer!",
    "results.completedTests": "Fullført",
    "results.tests": "tester",
    "common.loading": "Laster...",
    // Test page
    "test.loading": "Laster test...",
    "test.notFound": "Ordsett ikke funnet",
    "test.backToWordSets": "Tilbake til ordsett",
    "test.complete": "Test fullført!",
    "test.score": "Poeng",
    "test.correct": "Riktig",
    "test.timeSpent": "Tid brukt",
    "test.averageTime": "Gjennomsnittlig tid",
    "test.seconds": "sekunder",
    "test.restart": "Ta test igjen",
    "test.viewResults": "Se alle resultater",
    "test.listenToWord": "Lytt til ord",
    "test.yourAnswer": "Ditt svar:",
    "test.nextWord": "Neste ord",
    "test.finishTest": "Fullfør test",
    "test.progress": "Fremgang",
    "test.reviewMistakes": "Gjennomgå feil:",
    "test.reviewResults": "Gjennomgå alle ord:",
    "test.playAgain": "Spill igjen",
    "test.typeWordHere": "Skriv ordet her...",
    "test.correctSoFar": "Riktige så langt",
    "test.incorrect": "Feil",
    "test.tryAgain": "Prøv igjen",
    "test.attemptsRemaining": "Forsøk igjen",
    "common.of": "av",
  },
};

interface LanguageProviderProps {
  children: ReactNode;
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguage] = useState<Language>("no");

  const t = (key: string): string => {
    return (
      translations[language][
      key as keyof (typeof translations)[typeof language]
      ] || key
    );
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
