name: Deploy Frontend to Cloud Storage

# Required GitHub Secrets:
# - GCP_SA_KEY: Google Cloud Service Account JSON key
# - GOOGLE_CLOUD_PROJECT: Google Cloud Project ID
# - GCP_FRONTEND_BUCKET: Cloud Storage bucket name for frontend
# - GCP_REGION: Google Cloud region
# Production Firebase Configuration (optional, will use defaults if not set):
# - NEXT_PUBLIC_API_URL_PROD: Production API URL
# - NEXT_PUBLIC_FIREBASE_API_KEY_PROD: Firebase API key
# - NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN_PROD: Firebase auth domain
# - NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET_PROD: Firebase storage bucket
# - NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID_PROD: Firebase messaging sender ID
# - NEXT_PUBLIC_FIREBASE_APP_ID_PROD: Firebase app ID

on:
  push:
    branches: [main]
    paths: ['frontend/**']
  pull_request:
    branches: [main]
    paths: ['frontend/**']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup mise
        uses: jdx/mise-action@v2

      - name: Run tests
        run: mise run ci-test

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup mise
        uses: jdx/mise-action@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Build frontend
        env:
          GOOGLE_CLOUD_PROJECT: ${{ secrets.GOOGLE_CLOUD_PROJECT }}
          NEXT_PUBLIC_API_URL_PROD: ${{ secrets.NEXT_PUBLIC_API_URL_PROD }}
          NEXT_PUBLIC_FIREBASE_API_KEY_PROD: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY_PROD }}
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN_PROD: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN_PROD }}
          NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET_PROD: ${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET_PROD }}
          NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID_PROD: ${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID_PROD }}
          NEXT_PUBLIC_FIREBASE_APP_ID_PROD: ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID_PROD }}
        run: mise run ci-build-frontend

      - name: Deploy to Cloud Storage
        env:
          GCP_FRONTEND_BUCKET: ${{ secrets.GCP_FRONTEND_BUCKET }}
          GCP_REGION: ${{ secrets.GCP_REGION }}
          GCP_PROJECT_ID: ${{ secrets.GOOGLE_CLOUD_PROJECT }}
        run: mise run ci-deploy-frontend
